palette = "github_dark"
add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$rust\
$line_break\
$character"""

[fill]
symbol = ' '

[character]
success_symbol = '[>](bold blue)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](bold green)'

[directory]
style = 'bold blue'
read_only = ' ro'
truncation_length = 3
truncate_to_repo = true
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = 'bold purple'
truncation_length = 20
truncation_symbol = '...'

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold red'
ahead = '^${count} '
behind = 'v${count} '
diverged = '^${ahead_count}v${behind_count} '
conflicted = '= '
untracked = '? '
stashed = '* '
modified = '! '
staged = '+ '
renamed = '> '
deleted = 'x '

[cmd_duration]
min_time = 2000
format = '[$duration]($style) '
style = 'yellow'

[rust]
format = '[$version]($style) '
style = 'bold red'

[package]
disabled = true

[palettes.github_dark]
red = '#ff7b72'
green = '#7ee787'
yellow = '#d29922'
blue = '#79c0ff'
purple = '#d2a8ff'
cyan = '#a5d6ff'
orange = '#ffa657'
